### PR TITLE
Minor Website Updates

### PR DESCRIPTION
**Pull request by jagatfx**
- Added About page content from Bob
- Normalized most references to ERATECycle from E-Rate Cycle, ERATECycle, etc
- Removed gibberish text
- Adjusted hyperlinks to same color
- Filled out copyrights
- Switched buttons to link to other pages rather than to same page for better demo experience

### CODE REVIEW

**Comment by jagatfx** [comment]
@nnance for your review

**Comment by nicknswitchco** [comment]
+1.  merging now

**Comment by nnance** [comment]
+1 is this ready to merge?

**Comment by jagatfx** [comment]
@nnance yes. I was going to just add compliance to the existing branch but then realized you were about to merge so I created a new branch. However, I already pushed it to origin on this branch. So you'll get https://github.com/eratecycle/eratecycle.github.io/pull/33 changes in this merge.

**Pull request merged**
